# Generated by Django 3.2.16 on 2022-11-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20221112_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_info',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
