# Generated by Django 3.2.16 on 2022-11-13 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_restaurant_info_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant_review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('review', models.CharField(max_length=255)),
                ('restaurant_id', models.ForeignKey(db_column='restaurant_id', on_delete=django.db.models.deletion.CASCADE, to='content.restaurant_info')),
            ],
        ),
    ]
