# Generated by Django 3.2.16 on 2022-11-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_restaurant_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_review',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.restaurant_info'),
        ),
    ]
