# Generated by Django 3.2.16 on 2022-11-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_restaurant_review_restaurant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='bad_word',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='good_word',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=10)),
            ],
        ),
    ]
