# Generated by Django 3.2.16 on 2022-11-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_bad_word_good_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_review',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
