# Generated by Django 3.2.16 on 2022-11-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_rename_restaurant_id_restaurant_review_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_review',
            old_name='restaurant',
            new_name='restaurant_number',
        ),
    ]
