# Generated by Django 3.2.16 on 2022-11-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_rename_restaurant_restaurant_review_restaurant_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_review',
            old_name='restaurant_number',
            new_name='restaurant',
        ),
    ]
