# Generated by Django 3.2.16 on 2022-11-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_rename_restaurant_number_restaurant_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_word',
            name='word',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='good_word',
            name='word',
            field=models.CharField(max_length=30),
        ),
    ]
