# Generated by Django 3.2.16 on 2022-11-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20221125_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_word',
            name='word',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='good_word',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
